test:
  script:
      - whoami
      - id
      - echo "Test stage has been started" 
      - python3 --version ; pip --version  # For debugging
      - pip3 install -r requirements.txt --break-system-packages
      - pytest tests/test_app.py
      - pytest tests/test_black_box.py
      - pytest tests/test_white_box.py
  tags:
    - gcp

build:
  needs:
    - test
  script:
    - echo "Build stage has been started"
    - docker build -t gcr.io/black-journal-436122-b5/my-gitlab-app:latest .
  tags:
    - gcp

deploy:
  needs:
    - build
  script:
    - echo "Deploy stage has been started"
    - docker push gcr.io/black-journal-436122-b5/my-gitlab-app:latest
    - gcloud compute ssh myapp@myapp --zone=us-central1-c --command="sudo docker run -d gcr.io/black-journal-436122-b5/my-gitlab-app:latest"
  tags:
    - gcp

stages:
  - test
  - build
  - deploy