before_script:
  - python3 --version ; pip --version  # For debugging
  - pip3 install -r requirements.txt --break-system-packages
  # - python3 -m venv venv
  # - source venv/bin/activate

test:
  script:
      - echo "Test stage has been started" 
  tags:
    - gcp

build:
  script:
    - echo "Build stage has been started"
  tags:
    - gcp

deploy:
  script:
    - echo "Deploy stage has been started"
  tags:
    - gcp

stages:
  - test
  - build
  - deploy