before_script:
  - python --version ; pip --version  # For debugging
  - pip install -r requirements.txt

test:
  script:
      - echo "Test stage has been started" 
  tags:
    - gcp

build:
  script:
    - echo "Build stage has been started"
  tags:
    - gcp

deploy:
  script:
    - echo "Deploy stage has been started"
  tags:
    - gcp

stages:
  - test
  - build
  - deploy