test:
  script:
      - echo "Test stage has been started" 
      - python3 --version ; pip --version  # For debugging
      - pip3 install -r requirements.txt --break-system-packages
      - pytest tests/test_app.py
      - pytest tests/test_black_box.py
      - pytest tests/test_white_box.py
  tags:
    - gcp

build:
  needs:
    - test
  script:
    - echo "Build stage has been started"
    - docker build -t gcr.io/<PROJECT_ID_FROM_GOOGLE_CONSOLE>/my-gitlab-app:latest .
  tags:
    - gcp

deploy:
  needs:
    - build
  script:
    - echo "Deploy stage has been started"
    - docker push gcr.io/<PROJECT_ID_FROM_GOOGLE_CONSOLE>/my-gitlab-app:latest
    - gcloud compute ssh gitlab@<BACKEND_INSTANCE_NAME> --zone=<INSTANCE_ZONE> --command="sudo docker rm -f backend || echo 'No backend container'"
    - gcloud compute ssh gitlab@<BACKEND_INSTANCE_NAME> --zone=<INSTANCE_ZONE> --command="sudo docker pull gcr.io/<PROJECT_ID_FROM_GOOGLE_CONSOLE>/my-gitlab-app:latest"
    - gcloud compute ssh gitlab@<BACKEND_INSTANCE_NAME> --zone=<INSTANCE_ZONE> --command="sudo docker run -d --port 8080:8080 --name backend gcr.io/<PROJECT_ID_FROM_GOOGLE_CONSOLE>/my-gitlab-app:latest"
  tags:
    - gcp

stages:
  - test
  - build
  - deploy
